baseURL = "/"
languageCode = "de-DE"
title = "TFD Artworks"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""



  [params.logo]
    mobile = "ttfd.png" #images/logo-mobile.svg
    mobile_height = "" #36px
    mobile_width = "" #36px
    desktop = "ttfd.png" #images/logo.svg
    desktop_height = "tfd2.png" #29px
    desktop_width = ""#217px
    alt = "Logo"

  [params.homepage_meta_tags]
    meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Dienstleistung"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Projekte"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "Über uns"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 4

  [[menu.footer]]
      name = "Impressum"
      url = "/impressum/"
      weight = 1


[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
